///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ce60b0a8-ed91-440c-b871-b0f34d19a672")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyTestRepositoryFolders.TestAutomationForGUITestingRanoreAppFolder _testautomationforguitestingranore;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("ce60b0a8-ed91-440c-b871-b0f34d19a672")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "ce60b0a8-ed91-440c-b871-b0f34d19a672", ".\\RepositoryImages\\MyTestRepositoryce60b0a8.rximgres")
        {
            _applicationundertest = new MyTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _testautomationforguitestingranore = new MyTestRepositoryFolders.TestAutomationForGUITestingRanoreAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ce60b0a8-ed91-440c-b871-b0f34d19a672")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("a311bca1-afb5-4c08-b566-37ae8bd4331d")]
        public virtual MyTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The TestAutomationForGUITestingRanore folder.
        /// </summary>
        [RepositoryFolder("6033a74a-9ecb-4aa6-bfc1-6591e71232b2")]
        public virtual MyTestRepositoryFolders.TestAutomationForGUITestingRanoreAppFolder TestAutomationForGUITestingRanore
        {
            get { return _testautomationforguitestingranore; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("a311bca1-afb5-4c08-b566-37ae8bd4331d")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "a311bca1-afb5-4c08-b566-37ae8bd4331d", "")
            {
                _buttonInfo = new RepoItemInfo(this, "button", "?/?/section[2]/div/div[2]/a[@href>'https://www.ranorex.com/f' and @type=null() and @class='breakdance-link button-atom button-atom--custom bde-button__button']", "", 30000, null, "83655269-0d5d-4048-b2c2-2f78d026432c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a311bca1-afb5-4c08-b566-37ae8bd4331d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a311bca1-afb5-4c08-b566-37ae8bd4331d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The button item.
            /// </summary>
            [RepositoryItem("83655269-0d5d-4048-b2c2-2f78d026432c")]
            public virtual Ranorex.ATag button
            {
                get
                {
                    return _buttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The button item info.
            /// </summary>
            [RepositoryItemInfo("83655269-0d5d-4048-b2c2-2f78d026432c")]
            public virtual RepoItemInfo buttonInfo
            {
                get
                {
                    return _buttonInfo;
                }
            }
        }

        /// <summary>
        /// The TestAutomationForGUITestingRanoreAppFolder folder.
        /// </summary>
        [RepositoryFolder("6033a74a-9ecb-4aa6-bfc1-6591e71232b2")]
        public partial class TestAutomationForGUITestingRanoreAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _view1021Info;

            /// <summary>
            /// Creates a new TestAutomationForGUITestingRanore  folder.
            /// </summary>
            public TestAutomationForGUITestingRanoreAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TestAutomationForGUITestingRanore", "/form[@title>'Test Automation for GUI Testing']", parentFolder, 30000, null, true, "6033a74a-9ecb-4aa6-bfc1-6591e71232b2", "")
            {
                _view1021Info = new RepoItemInfo(this, "View1021", "container[@name>'Test Automation for GUI Testing']//toolbar[@automationid='view_1000']/container[@classname='LocationBarView']/text[@automationid='view_1021']", "", 30000, null, "c71beb11-60ff-41c0-81c4-665ac1dee541");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6033a74a-9ecb-4aa6-bfc1-6591e71232b2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6033a74a-9ecb-4aa6-bfc1-6591e71232b2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The View1021 item.
            /// </summary>
            [RepositoryItem("c71beb11-60ff-41c0-81c4-665ac1dee541")]
            public virtual Ranorex.Text View1021
            {
                get
                {
                    return _view1021Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The View1021 item info.
            /// </summary>
            [RepositoryItemInfo("c71beb11-60ff-41c0-81c4-665ac1dee541")]
            public virtual RepoItemInfo View1021Info
            {
                get
                {
                    return _view1021Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
